/** \file
 *  This C source file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : /Users/mcc/work/h/hello/desktop/basic.g
 *     -                            On : 2011-09-05 21:37:10
 *     -                for the parser : basicParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "basicParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pbasicParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pbasicParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pbasicParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pbasicParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER				ctx->pParser  
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   basicParserTokenNames[38+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "WHITE",
        (pANTLR3_UINT8) "LINEN",
        (pANTLR3_UINT8) "PRINT",
        (pANTLR3_UINT8) "GOTO",
        (pANTLR3_UINT8) "TRASHY",
        (pANTLR3_UINT8) "REM",
        (pANTLR3_UINT8) "LOAD",
        (pANTLR3_UINT8) "SAVE",
        (pANTLR3_UINT8) "RUN",
        (pANTLR3_UINT8) "CATALOG",
        (pANTLR3_UINT8) "LIST",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "P",
        (pANTLR3_UINT8) "R",
        (pANTLR3_UINT8) "I",
        (pANTLR3_UINT8) "N",
        (pANTLR3_UINT8) "T",
        (pANTLR3_UINT8) "G",
        (pANTLR3_UINT8) "O",
        (pANTLR3_UINT8) "E",
        (pANTLR3_UINT8) "M",
        (pANTLR3_UINT8) "L",
        (pANTLR3_UINT8) "A",
        (pANTLR3_UINT8) "D",
        (pANTLR3_UINT8) "S",
        (pANTLR3_UINT8) "V",
        (pANTLR3_UINT8) "U",
        (pANTLR3_UINT8) "C",
        (pANTLR3_UINT8) "B",
        (pANTLR3_UINT8) "F",
        (pANTLR3_UINT8) "H",
        (pANTLR3_UINT8) "J",
        (pANTLR3_UINT8) "K",
        (pANTLR3_UINT8) "Q",
        (pANTLR3_UINT8) "W",
        (pANTLR3_UINT8) "X",
        (pANTLR3_UINT8) "Y",
        (pANTLR3_UINT8) "Z"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static basicParser_start_return	start    (pbasicParser ctx);
static basicParser_command_return	command    (pbasicParser ctx);
static basicParser_statement_return	statement    (pbasicParser ctx);
static basicParser_onearg_return	onearg    (pbasicParser ctx);
static basicParser_noarg_return	noarg    (pbasicParser ctx);
static basicParser_expr_return	expr    (pbasicParser ctx);
static void	basicParserFree(pbasicParser ctx);
static void     basicParserReset (pbasicParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/Users/mcc/work/h/hello/desktop/basic.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new basicParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pbasicParser
basicParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return basicParserNewSSD(instream, NULL);
}

/** \brief Create a new basicParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pbasicParser
basicParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pbasicParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pbasicParser) ANTLR3_CALLOC(1, sizeof(basicParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in basicParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our basicParser interface
     */
    ctx->start	= start;
    ctx->command	= command;
    ctx->statement	= statement;
    ctx->onearg	= onearg;
    ctx->noarg	= noarg;
    ctx->expr	= expr;
    ctx->free			= basicParserFree;
    ctx->reset			= basicParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(0);
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = basicParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
basicParserReset (pbasicParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 basicParserFree(pbasicParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return basicParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_start48  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_start48_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000007EE0) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_start48	= { FOLLOW_WHITE_in_start48_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_command_in_start51  */
static	ANTLR3_BITWORD FOLLOW_command_in_start51_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_command_in_start51	= { FOLLOW_command_in_start51_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_start53  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_start53_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_start53	= { FOLLOW_EOF_in_start53_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LINEN_in_command70  */
static	ANTLR3_BITWORD FOLLOW_LINEN_in_command70_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000007EE0) };
static  ANTLR3_BITSET_LIST FOLLOW_LINEN_in_command70	= { FOLLOW_LINEN_in_command70_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_command72  */
static	ANTLR3_BITWORD FOLLOW_statement_in_command72_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_command72	= { FOLLOW_statement_in_command72_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_command85  */
static	ANTLR3_BITWORD FOLLOW_statement_in_command85_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_command85	= { FOLLOW_statement_in_command85_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRINT_in_statement102  */
static	ANTLR3_BITWORD FOLLOW_PRINT_in_statement102_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008010) };
static  ANTLR3_BITSET_LIST FOLLOW_PRINT_in_statement102	= { FOLLOW_PRINT_in_statement102_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_statement104  */
static	ANTLR3_BITWORD FOLLOW_expr_in_statement104_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_statement104	= { FOLLOW_expr_in_statement104_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_GOTO_in_statement117  */
static	ANTLR3_BITWORD FOLLOW_GOTO_in_statement117_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000030) };
static  ANTLR3_BITSET_LIST FOLLOW_GOTO_in_statement117	= { FOLLOW_GOTO_in_statement117_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_statement119  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_statement119_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_statement119	= { FOLLOW_WHITE_in_statement119_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LINEN_in_statement122  */
static	ANTLR3_BITWORD FOLLOW_LINEN_in_statement122_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_LINEN_in_statement122	= { FOLLOW_LINEN_in_statement122_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_onearg_in_statement135  */
static	ANTLR3_BITWORD FOLLOW_onearg_in_statement135_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000102) };
static  ANTLR3_BITSET_LIST FOLLOW_onearg_in_statement135	= { FOLLOW_onearg_in_statement135_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TRASHY_in_statement137  */
static	ANTLR3_BITWORD FOLLOW_TRASHY_in_statement137_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000102) };
static  ANTLR3_BITSET_LIST FOLLOW_TRASHY_in_statement137	= { FOLLOW_TRASHY_in_statement137_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_noarg_in_statement149  */
static	ANTLR3_BITWORD FOLLOW_noarg_in_statement149_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000012) };
static  ANTLR3_BITSET_LIST FOLLOW_noarg_in_statement149	= { FOLLOW_noarg_in_statement149_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_statement151  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_statement151_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_statement151	= { FOLLOW_WHITE_in_statement151_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_onearg0  */
static	ANTLR3_BITWORD FOLLOW_set_in_onearg0_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_onearg0	= { FOLLOW_set_in_onearg0_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_noarg0  */
static	ANTLR3_BITWORD FOLLOW_set_in_noarg0_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_noarg0	= { FOLLOW_set_in_noarg0_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_expr198  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_expr198_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_expr198	= { FOLLOW_WHITE_in_expr198_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_expr201  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_expr201_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_expr201	= { FOLLOW_STRING_in_expr201_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start start
 * /Users/mcc/work/h/hello/desktop/basic.g:10:1: start : ( WHITE )? command EOF -> command ;
 */
static basicParser_start_return
start(pbasicParser ctx)
{   
    basicParser_start_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    WHITE1;
    pANTLR3_COMMON_TOKEN    EOF3;
    basicParser_command_return command2;
    #undef	RETURN_TYPE_command2
    #define	RETURN_TYPE_command2 basicParser_command_return

    pANTLR3_BASE_TREE WHITE1_tree;
    pANTLR3_BASE_TREE EOF3_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_WHITE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_EOF;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_command;
    /* Initialize rule variables
     */


    root_0 = NULL;

    WHITE1       = NULL;
    EOF3       = NULL;
    command2.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    WHITE1_tree   = NULL;
    EOF3_tree   = NULL;

    stream_WHITE   = NULL;
    #define CREATE_stream_WHITE  if (stream_WHITE == NULL) {stream_WHITE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token WHITE"); } 
    stream_EOF   = NULL;
    #define CREATE_stream_EOF  if (stream_EOF == NULL) {stream_EOF = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token EOF"); } 
    stream_command   = NULL;
    #define CREATE_stream_command  if (stream_command == NULL) {stream_command = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule command"); }

    retval.tree  = NULL;
    {
        // /Users/mcc/work/h/hello/desktop/basic.g:10:7: ( ( WHITE )? command EOF -> command )
        // /Users/mcc/work/h/hello/desktop/basic.g:10:9: ( WHITE )? command EOF
        {

            // /Users/mcc/work/h/hello/desktop/basic.g:10:9: ( WHITE )?
            {
                int alt1=2;
                switch ( LA(1) ) 
                {
                    case WHITE:
                    	{
                    		alt1=1;
                    	}
                        break;
                }

                switch (alt1) 
                {
            	case 1:
            	    // /Users/mcc/work/h/hello/desktop/basic.g:10:9: WHITE
            	    {
            	        WHITE1 = (pANTLR3_COMMON_TOKEN) MATCHT(WHITE, &FOLLOW_WHITE_in_start48); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestartEx;
            	        }
            	         
            	        CREATE_stream_WHITE; stream_WHITE->add(stream_WHITE, WHITE1, NULL);


            	    }
            	    break;

                }
            }
            FOLLOWPUSH(FOLLOW_command_in_start51);
            command2=command(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestartEx;
            }

            CREATE_stream_command; stream_command->add(stream_command, command2.tree, NULL);
            EOF3 = (pANTLR3_COMMON_TOKEN) MATCHT(EOF, &FOLLOW_EOF_in_start53); 
            if  (HASEXCEPTION())
            {
                goto rulestartEx;
            }
             
            CREATE_stream_EOF; stream_EOF->add(stream_EOF, EOF3, NULL);


             
            /* AST REWRITE
             * elements          : command
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 10:28: -> command
            	{
            	    ADAPTOR->addChild(ADAPTOR, root_0, stream_command == NULL ? NULL : stream_command->nextTree(stream_command));

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulestartEx; /* Prevent compiler warnings */
    rulestartEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_WHITE != NULL) stream_WHITE->free(stream_WHITE);
        if (stream_EOF != NULL) stream_EOF->free(stream_EOF);
        if (stream_command != NULL) stream_command->free(stream_command);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end start */

/** 
 * $ANTLR start command
 * /Users/mcc/work/h/hello/desktop/basic.g:13:1: command : ( LINEN statement -> ^( LINEN statement ) | statement -> statement );
 */
static basicParser_command_return
command(pbasicParser ctx)
{   
    basicParser_command_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    LINEN4;
    basicParser_statement_return statement5;
    #undef	RETURN_TYPE_statement5
    #define	RETURN_TYPE_statement5 basicParser_statement_return

    basicParser_statement_return statement6;
    #undef	RETURN_TYPE_statement6
    #define	RETURN_TYPE_statement6 basicParser_statement_return

    pANTLR3_BASE_TREE LINEN4_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_LINEN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_statement;
    /* Initialize rule variables
     */


    root_0 = NULL;

    LINEN4       = NULL;
    statement5.tree = NULL;
    statement6.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    LINEN4_tree   = NULL;

    stream_LINEN   = NULL;
    #define CREATE_stream_LINEN  if (stream_LINEN == NULL) {stream_LINEN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token LINEN"); } 
    stream_statement   = NULL;
    #define CREATE_stream_statement  if (stream_statement == NULL) {stream_statement = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule statement"); }

    retval.tree  = NULL;
    {
        {
            //  /Users/mcc/work/h/hello/desktop/basic.g:14:2: ( LINEN statement -> ^( LINEN statement ) | statement -> statement )
            
            ANTLR3_UINT32 alt2;

            alt2=2;

            switch ( LA(1) ) 
            {
            case LINEN:
            	{
            		alt2=1;
            	}
                break;
            case PRINT:
            case GOTO:
            case REM:
            case LOAD:
            case SAVE:
            case RUN:
            case CATALOG:
            case LIST:
            	{
            		alt2=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulecommandEx;
            }

            switch (alt2) 
            {
        	case 1:
        	    // /Users/mcc/work/h/hello/desktop/basic.g:14:4: LINEN statement
        	    {
        	        LINEN4 = (pANTLR3_COMMON_TOKEN) MATCHT(LINEN, &FOLLOW_LINEN_in_command70); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }
        	         
        	        CREATE_stream_LINEN; stream_LINEN->add(stream_LINEN, LINEN4, NULL);

        	        FOLLOWPUSH(FOLLOW_statement_in_command72);
        	        statement5=statement(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }

        	        CREATE_stream_statement; stream_statement->add(stream_statement, statement5.tree, NULL);

        	         
        	        /* AST REWRITE
        	         * elements          : LINEN, statement
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 14:20: -> ^( LINEN statement )
        	        	{
        	        	    // /Users/mcc/work/h/hello/desktop/basic.g:14:23: ^( LINEN statement )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_LINEN == NULL ? NULL : stream_LINEN->nextNode(stream_LINEN), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_statement == NULL ? NULL : stream_statement->nextTree(stream_statement));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // /Users/mcc/work/h/hello/desktop/basic.g:15:4: statement
        	    {
        	        FOLLOWPUSH(FOLLOW_statement_in_command85);
        	        statement6=statement(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }

        	        CREATE_stream_statement; stream_statement->add(stream_statement, statement6.tree, NULL);

        	         
        	        /* AST REWRITE
        	         * elements          : statement
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 15:15: -> statement
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_statement == NULL ? NULL : stream_statement->nextTree(stream_statement));

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulecommandEx; /* Prevent compiler warnings */
    rulecommandEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_LINEN != NULL) stream_LINEN->free(stream_LINEN);
        if (stream_statement != NULL) stream_statement->free(stream_statement);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end command */

/** 
 * $ANTLR start statement
 * /Users/mcc/work/h/hello/desktop/basic.g:18:1: statement : ( PRINT expr -> ^( PRINT expr ) | GOTO ( WHITE )? LINEN -> ^( GOTO LINEN ) | onearg ( TRASHY )* -> ^( onearg ) | noarg ( WHITE )? );
 */
static basicParser_statement_return
statement(pbasicParser ctx)
{   
    basicParser_statement_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PRINT7;
    pANTLR3_COMMON_TOKEN    GOTO9;
    pANTLR3_COMMON_TOKEN    WHITE10;
    pANTLR3_COMMON_TOKEN    LINEN11;
    pANTLR3_COMMON_TOKEN    TRASHY13;
    pANTLR3_COMMON_TOKEN    WHITE15;
    basicParser_expr_return expr8;
    #undef	RETURN_TYPE_expr8
    #define	RETURN_TYPE_expr8 basicParser_expr_return

    basicParser_onearg_return onearg12;
    #undef	RETURN_TYPE_onearg12
    #define	RETURN_TYPE_onearg12 basicParser_onearg_return

    basicParser_noarg_return noarg14;
    #undef	RETURN_TYPE_noarg14
    #define	RETURN_TYPE_noarg14 basicParser_noarg_return

    pANTLR3_BASE_TREE PRINT7_tree;
    pANTLR3_BASE_TREE GOTO9_tree;
    pANTLR3_BASE_TREE WHITE10_tree;
    pANTLR3_BASE_TREE LINEN11_tree;
    pANTLR3_BASE_TREE TRASHY13_tree;
    pANTLR3_BASE_TREE WHITE15_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_WHITE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_LINEN;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_GOTO;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_TRASHY;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_PRINT;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_onearg;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    PRINT7       = NULL;
    GOTO9       = NULL;
    WHITE10       = NULL;
    LINEN11       = NULL;
    TRASHY13       = NULL;
    WHITE15       = NULL;
    expr8.tree = NULL;
    onearg12.tree = NULL;
    noarg14.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    PRINT7_tree   = NULL;
    GOTO9_tree   = NULL;
    WHITE10_tree   = NULL;
    LINEN11_tree   = NULL;
    TRASHY13_tree   = NULL;
    WHITE15_tree   = NULL;

    stream_WHITE   = NULL;
    #define CREATE_stream_WHITE  if (stream_WHITE == NULL) {stream_WHITE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token WHITE"); } 
    stream_LINEN   = NULL;
    #define CREATE_stream_LINEN  if (stream_LINEN == NULL) {stream_LINEN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token LINEN"); } 
    stream_GOTO   = NULL;
    #define CREATE_stream_GOTO  if (stream_GOTO == NULL) {stream_GOTO = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token GOTO"); } 
    stream_TRASHY   = NULL;
    #define CREATE_stream_TRASHY  if (stream_TRASHY == NULL) {stream_TRASHY = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token TRASHY"); } 
    stream_PRINT   = NULL;
    #define CREATE_stream_PRINT  if (stream_PRINT == NULL) {stream_PRINT = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token PRINT"); } 
    stream_onearg   = NULL;
    #define CREATE_stream_onearg  if (stream_onearg == NULL) {stream_onearg = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule onearg"); }
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;
    {
        {
            //  /Users/mcc/work/h/hello/desktop/basic.g:19:2: ( PRINT expr -> ^( PRINT expr ) | GOTO ( WHITE )? LINEN -> ^( GOTO LINEN ) | onearg ( TRASHY )* -> ^( onearg ) | noarg ( WHITE )? )
            
            ANTLR3_UINT32 alt6;

            alt6=4;

            switch ( LA(1) ) 
            {
            case PRINT:
            	{
            		alt6=1;
            	}
                break;
            case GOTO:
            	{
            		alt6=2;
            	}
                break;
            case REM:
            case LOAD:
            case SAVE:
            case RUN:
            	{
            		alt6=3;
            	}
                break;
            case CATALOG:
            case LIST:
            	{
            		alt6=4;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto rulestatementEx;
            }

            switch (alt6) 
            {
        	case 1:
        	    // /Users/mcc/work/h/hello/desktop/basic.g:19:4: PRINT expr
        	    {
        	        PRINT7 = (pANTLR3_COMMON_TOKEN) MATCHT(PRINT, &FOLLOW_PRINT_in_statement102); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }
        	         
        	        CREATE_stream_PRINT; stream_PRINT->add(stream_PRINT, PRINT7, NULL);

        	        FOLLOWPUSH(FOLLOW_expr_in_statement104);
        	        expr8=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr8.tree, NULL);

        	         
        	        /* AST REWRITE
        	         * elements          : PRINT, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 19:15: -> ^( PRINT expr )
        	        	{
        	        	    // /Users/mcc/work/h/hello/desktop/basic.g:19:18: ^( PRINT expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_PRINT == NULL ? NULL : stream_PRINT->nextNode(stream_PRINT), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // /Users/mcc/work/h/hello/desktop/basic.g:20:4: GOTO ( WHITE )? LINEN
        	    {
        	        GOTO9 = (pANTLR3_COMMON_TOKEN) MATCHT(GOTO, &FOLLOW_GOTO_in_statement117); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }
        	         
        	        CREATE_stream_GOTO; stream_GOTO->add(stream_GOTO, GOTO9, NULL);


        	        // /Users/mcc/work/h/hello/desktop/basic.g:20:9: ( WHITE )?
        	        {
        	            int alt3=2;
        	            switch ( LA(1) ) 
        	            {
        	                case WHITE:
        	                	{
        	                		alt3=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt3) 
        	            {
        	        	case 1:
        	        	    // /Users/mcc/work/h/hello/desktop/basic.g:20:9: WHITE
        	        	    {
        	        	        WHITE10 = (pANTLR3_COMMON_TOKEN) MATCHT(WHITE, &FOLLOW_WHITE_in_statement119); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulestatementEx;
        	        	        }
        	        	         
        	        	        CREATE_stream_WHITE; stream_WHITE->add(stream_WHITE, WHITE10, NULL);


        	        	    }
        	        	    break;

        	            }
        	        }
        	        LINEN11 = (pANTLR3_COMMON_TOKEN) MATCHT(LINEN, &FOLLOW_LINEN_in_statement122); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }
        	         
        	        CREATE_stream_LINEN; stream_LINEN->add(stream_LINEN, LINEN11, NULL);


        	         
        	        /* AST REWRITE
        	         * elements          : LINEN, GOTO
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 20:22: -> ^( GOTO LINEN )
        	        	{
        	        	    // /Users/mcc/work/h/hello/desktop/basic.g:20:25: ^( GOTO LINEN )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_GOTO == NULL ? NULL : stream_GOTO->nextNode(stream_GOTO), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_LINEN == NULL ? NULL : stream_LINEN->nextNode(stream_LINEN));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // /Users/mcc/work/h/hello/desktop/basic.g:21:4: onearg ( TRASHY )*
        	    {
        	        FOLLOWPUSH(FOLLOW_onearg_in_statement135);
        	        onearg12=onearg(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }

        	        CREATE_stream_onearg; stream_onearg->add(stream_onearg, onearg12.tree, NULL);

        	        // /Users/mcc/work/h/hello/desktop/basic.g:21:11: ( TRASHY )*

        	        for (;;)
        	        {
        	            int alt4=2;
        	            switch ( LA(1) ) 
        	            {
        	            case TRASHY:
        	            	{
        	            		alt4=1;
        	            	}
        	                break;

        	            }

        	            switch (alt4) 
        	            {
        	        	case 1:
        	        	    // /Users/mcc/work/h/hello/desktop/basic.g:21:11: TRASHY
        	        	    {
        	        	        TRASHY13 = (pANTLR3_COMMON_TOKEN) MATCHT(TRASHY, &FOLLOW_TRASHY_in_statement137); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulestatementEx;
        	        	        }
        	        	         
        	        	        CREATE_stream_TRASHY; stream_TRASHY->add(stream_TRASHY, TRASHY13, NULL);


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop4;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop4: ; /* Jump out to here if this rule does not match */


        	         
        	        /* AST REWRITE
        	         * elements          : onearg
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 21:19: -> ^( onearg )
        	        	{
        	        	    // /Users/mcc/work/h/hello/desktop/basic.g:21:22: ^( onearg )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_onearg == NULL ? NULL : stream_onearg->nextNode(stream_onearg), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 4:
        	    // /Users/mcc/work/h/hello/desktop/basic.g:22:4: noarg ( WHITE )?
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_noarg_in_statement149);
        	        noarg14=noarg(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, noarg14.tree);

        	        // /Users/mcc/work/h/hello/desktop/basic.g:22:10: ( WHITE )?
        	        {
        	            int alt5=2;
        	            switch ( LA(1) ) 
        	            {
        	                case WHITE:
        	                	{
        	                		alt5=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt5) 
        	            {
        	        	case 1:
        	        	    // /Users/mcc/work/h/hello/desktop/basic.g:22:10: WHITE
        	        	    {
        	        	        WHITE15 = (pANTLR3_COMMON_TOKEN) MATCHT(WHITE, &FOLLOW_WHITE_in_statement151); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulestatementEx;
        	        	        }

        	        	        WHITE15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, WHITE15));
        	        	        ADAPTOR->addChild(ADAPTOR, root_0, WHITE15_tree);


        	        	    }
        	        	    break;

        	            }
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_WHITE != NULL) stream_WHITE->free(stream_WHITE);
        if (stream_LINEN != NULL) stream_LINEN->free(stream_LINEN);
        if (stream_GOTO != NULL) stream_GOTO->free(stream_GOTO);
        if (stream_TRASHY != NULL) stream_TRASHY->free(stream_TRASHY);
        if (stream_PRINT != NULL) stream_PRINT->free(stream_PRINT);
        if (stream_onearg != NULL) stream_onearg->free(stream_onearg);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end statement */

/** 
 * $ANTLR start onearg
 * /Users/mcc/work/h/hello/desktop/basic.g:26:1: onearg : ( REM | LOAD | SAVE | RUN );
 */
static basicParser_onearg_return
onearg(pbasicParser ctx)
{   
    basicParser_onearg_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set16;

    pANTLR3_BASE_TREE set16_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set16       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    set16_tree   = NULL;


    retval.tree  = NULL;
    {
        // /Users/mcc/work/h/hello/desktop/basic.g:26:9: ( REM | LOAD | SAVE | RUN )
        // /Users/mcc/work/h/hello/desktop/basic.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            set16=(pANTLR3_COMMON_TOKEN)LT(1);
            if ( ((LA(1) >= REM) && (LA(1) <= RUN)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set16)));
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_onearg0;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_onearg0);    goto ruleoneargEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleoneargEx; /* Prevent compiler warnings */
    ruleoneargEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end onearg */

/** 
 * $ANTLR start noarg
 * /Users/mcc/work/h/hello/desktop/basic.g:27:1: noarg : ( CATALOG | LIST );
 */
static basicParser_noarg_return
noarg(pbasicParser ctx)
{   
    basicParser_noarg_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set17;

    pANTLR3_BASE_TREE set17_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set17       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    set17_tree   = NULL;


    retval.tree  = NULL;
    {
        // /Users/mcc/work/h/hello/desktop/basic.g:27:7: ( CATALOG | LIST )
        // /Users/mcc/work/h/hello/desktop/basic.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            set17=(pANTLR3_COMMON_TOKEN)LT(1);
            if ( ((LA(1) >= CATALOG) && (LA(1) <= LIST)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set17)));
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_noarg0;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_noarg0);    goto rulenoargEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulenoargEx; /* Prevent compiler warnings */
    rulenoargEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end noarg */

/** 
 * $ANTLR start expr
 * /Users/mcc/work/h/hello/desktop/basic.g:29:1: expr : ( WHITE )? STRING ;
 */
static basicParser_expr_return
expr(pbasicParser ctx)
{   
    basicParser_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    WHITE18;
    pANTLR3_COMMON_TOKEN    STRING19;

    pANTLR3_BASE_TREE WHITE18_tree;
    pANTLR3_BASE_TREE STRING19_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    WHITE18       = NULL;
    STRING19       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    WHITE18_tree   = NULL;
    STRING19_tree   = NULL;


    retval.tree  = NULL;
    {
        // /Users/mcc/work/h/hello/desktop/basic.g:30:2: ( ( WHITE )? STRING )
        // /Users/mcc/work/h/hello/desktop/basic.g:30:4: ( WHITE )? STRING
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // /Users/mcc/work/h/hello/desktop/basic.g:30:4: ( WHITE )?
            {
                int alt7=2;
                switch ( LA(1) ) 
                {
                    case WHITE:
                    	{
                    		alt7=1;
                    	}
                        break;
                }

                switch (alt7) 
                {
            	case 1:
            	    // /Users/mcc/work/h/hello/desktop/basic.g:30:4: WHITE
            	    {
            	        WHITE18 = (pANTLR3_COMMON_TOKEN) MATCHT(WHITE, &FOLLOW_WHITE_in_expr198); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        WHITE18_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, WHITE18));
            	        ADAPTOR->addChild(ADAPTOR, root_0, WHITE18_tree);


            	    }
            	    break;

                }
            }
            STRING19 = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_expr201); 
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            STRING19_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, STRING19));
            ADAPTOR->addChild(ADAPTOR, root_0, STRING19_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end expr */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
