<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rules</string>
	</array>
	<key>name</key>
	<string>Make.rules</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.makepy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(?:(?!(?:if|elif|else|for|do|global|import|include)\b)(\S[^:]*)|(do|global)\s*):.*</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.makepy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.makepy</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.makepy</string>
			<key>end</key>
			<string>^(?!\1\s)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(?:if|elif|else|print|warn|error|do|global|import|include)\b</string>
			<key>name</key>
			<string>keyword.control.makepy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.makepy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.makepy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(python)\s+([^#]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.makepy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.makepy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.makepy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(for)\s+(\S+)\s+(in)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.makepy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.makepy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(env(?:raw)?\s+)?(\S+)(?=\s*\W?=)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.makepy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.makepy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(env(?:raw)?)\s+(\S+)\s*(\#|$)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$?\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>string.quoted.makepy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\$?"(\\.|[^\\"])*"</string>
			<key>name</key>
			<string>string.quoted.makepy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$\w+</string>
			<key>name</key>
			<string>variable.other.makepy</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.makepy</string>
	<key>uuid</key>
	<string>4882ba71-67a5-47db-b7e2-c1cef6b4d0bf</string>
</dict>
</plist>
